#+title: Example 1
#+author: Alexander E. Zarebski /et al/
#+options: h:1 num:t toc:nil

* Learning goals

- Read CSV into memory
- Compute summary statistics
- Generate random variables
- Learn how to plot
  + Scatter plot
  + Histogram
  + Function (PMF)
- Spotting outliers
- Basic hypothesis test: Fisher's exact test
- Check assumptions of model
- Basic parameter estimate: MLE with Wald CI
- Explain methodology above

* Example outline

The students will be given a data set containing the results of \(N\) coin flips
from each of \(M\) people and guided through some basic exploratory analysis and
testing whether the coins are biased. The data set will have some outliers in it
that they will be required to identify and remove and there will be a
permutation of the flip numbers which invalidates their model but will still
lead to the correct result. This will hopefully illustrate the importance of
checking model assumptions.

** Simulate and plot a binomial distribution
*** Simulate random variables with a binomial distribution
*** Confirm properties of the binomial distribution that we'll need for later: mean and variance
** Read in data from a CSV
*** I will supply a data set as a CSV with the following header.

#+BEGIN_SRC csv
name,flip_number,outcome
#+END_SRC

- The =name= is the name of the coin flipper
- The =flip_number= indicates the number coin flip it is
- The =outcome= is either =heads= or =tails=

There will be some outliers and the =flip_number= will be permuted so as to
introduce an autocorrelation which they will need to spot in a subsequent task.

*** Summarise the data as total trials and total heads
*** Summarise as proportion heads stratified by person
** Basic plots and summary statistics of the data
*** Generate histograms and spot the outliers
*** Overlay a plot of the density of the binomial distribution
** Fisher exact test for outliers
*** Apply Fisher's exact test to have a formal result suggesting they are outliers
*** Filter those outliers out of the data set
*** Remove the outliers in the original data set and then recompute the summary statistics
** Estimate the probability of heads and if the coins are fair
*** Estimate probability and generate the CI using Wald's method and interpret that
*** Simulate 20 data sets to test the coverage is as expected
** Look for anomaly in the data
*** Plot the points as a time series to discover that there is a temporal trend in the coin results
*** Interpret how this feature of the data limits the results of their work: data does not match IID assumption

* Materials
** Dataset
** Jupyter notebook
