#+title: Applied Analytic Statistics

The notebooks in this repository are being written for use in the course Applied
Analytic Statistics. Each of the directories, =example-<n>= contains two
notebooks: =example-<n>-questions.ipynb= and =example-<n>-answers.ipynb=. The
/questions/ notebook contains the questions for the practical sessions and the
/answers/ one has partial answers. Please give the questions a solid attempt
before looking at the answers as this is the best way to check that you really
understand them.

*Please note*: we are in the process of revising the tutorial notebooks on a
weekly basis based on the lectures and previous sessions. As such, you will need
to pull down changes from the main branch each week for the tutorial.

* Contents

- [[https://github.com/aezarebski/aas-extended-examples/tree/main/example-0][Example 0]] contains an overview of the software packages we will be using and
  basic python skills (primarily plotting with matplotlib).
- [[https://github.com/aezarebski/aas-extended-examples/tree/main/example-1][Example 1]] reviews the central limit theorem and looks at confidence intervals
  and hypothesis tests.
- [[https://github.com/aezarebski/aas-extended-examples/tree/main/example-2][Example 2]] reviews simple linear regression.
- The [[https://github.com/aezarebski/aas-extended-examples/blob/main/setup.org][setup]] page gives some instructions for setting up the software and
  notebooks.

* Additional Resources

In addition to the [[https://socialsciences.mcmaster.ca/jfox/Books/Applied-Regression-3E/index.html][course text book]] the I recommend the book, [[https://python.swaroopch.com/][A Byte of Python]]
for those relatively new to programming. For an overview of the packages we will
be using in this course see =example-0= and for help getting started look at =setup.org=.
