* Applied Analytic Statistics

The notebooks in this repository are being written for use in the course Applied
Analytic Statistics. Each of the directories, =example-<n>= contains two
notesbooks: =example-<n>-questions.ipynb= and =example-<n>-answers.ipynb=. The
/questions/ notebook contains the questions for the practical sessions and the
/answers/ one has partial answers. Please give the questions a solid attempt
before looking at the answers. For some examples there is a
=example-<n>-data.ipynb= which contains code to simulate data for those examples
which make use of simulated data.

In addition to the [[https://socialsciences.mcmaster.ca/jfox/Books/Applied-Regression-3E/index.html][course text book]] the I recommend the book, [[https://python.swaroopch.com/][A Byte of Python]]
for those relatively new to programming. For an overview of the packages we will
be using in this course see [[file:./example-0/welcome.ipynb][this notebook]].

** Jupyter Lab

To keep the notebooks in a neat state, please restart the kernel and run all
cells prior to commiting any changes.

The =shell.nix= file describes a package for running the notebooks in this
repository. To activate the notebook server run the following command.

#+begin_src sh
nix-shell --command "jupyter lab"
#+end_src

The =shell.nix= file is based on the instructions provided by [[https://github.com/tweag/jupyterWith#jupyterwith][jupyterWith
repository]] from Tweag.

** Pandoc

The pandoc tool is very useful for moving between different formats of notebook.

#+begin_src sh
  nix-shell -p pandoc
  pandoc example-n-answers.org -o example-n-answers.ipynb
#+end_src

This gets 90% of the conversion done, you just need to step through the notebook
in JupyterLab to check it formatted correctly.
