* Example 3

In this example we again help Professor Mittens analyse some data. However, to
make use of some useful packages from R we will consider an R script in addition
to the python notebook. The following might be useful in helping you to install
R and the necessary packages.

** Installing R

*** Method 1: Rstudio (ADVISED)

This is the method I would advise for those new to R and who like working in an
IDE. Rstudio is the best IDE for R and they do a very good job of streamlining
the setup process. There are instructions on how to install Rstudio and R
available at the following link:

https://rstudio-education.github.io/hopr/starting.html

*** Method 2: Conda

Anaconda has instructions for setting up R at the following link:

https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/

*** Method 3: Direct from CRAN (DIFFICULT)

Unless you are very comfortable installing software, I would advise against this
approach. You can download binaries or the source from CRAN. The following link
explains how to do this:

https://cran.r-project.org/doc/manuals/r-release/R-admin.html

If you are an Emacs user, then you might find Emacs Speaks Statistics helpful.

** Installing packages

CRAN is a repository of trustworthy R packages. To install the package =ggplot2=
from CRAN run the following commands at the command prompt in R.

#+begin_src R
install.packages("ggplot2")  
#+end_src
